import { PrismaClient } from "@prisma/client/extension";

const products = [
  {
    name: "Modern Sofa",
    description: "A comfortable modern sofa with a sleek design.",
    price: 599.99,
    stock: 10,
    category: "Sofa",
    brand: "HomeComfort",
    imageUrl: "https://example.com/images/modern-sofa.jpg",
    material: "Fabric",
    dimensions: "200x90x75 cm",
    weight: 50.5,
    color: "Gray",
    style: "Minimalist",
    room: "Living Room",
    assemblyRequired: true,
    warrantyPeriod: 24,
    loadCapacity: 300.0,
    seatingCapacity: 3,
    adjustableFeatures: "Recline",
  },
  {
    name: "Wooden Dining Table",
    description: "A sturdy dining table made from solid oak wood.",
    price: 799.99,
    stock: 5,
    category: "Table",
    brand: "Rustic Charm",
    imageUrl: "https://example.com/images/dining-table.jpg",
    material: "Oak Wood",
    dimensions: "150x90x75 cm",
    weight: 70.0,
    color: "Brown",
    style: "Rustic",
    room: "Dining Room",
    assemblyRequired: false,
    warrantyPeriod: 36,
    loadCapacity: 500.0,
    seatingCapacity: 6,
    adjustableFeatures: null,
  },
  {
    name: "Ergonomic Office Chair",
    description: "A high-back ergonomic office chair with adjustable features.",
    price: 199.99,
    stock: 25,
    category: "Chair",
    brand: "OfficePro",
    imageUrl: "https://example.com/images/office-chair.jpg",
    material: "Mesh and Metal",
    dimensions: "60x60x120 cm",
    weight: 12.5,
    color: "Black",
    style: "Modern",
    room: "Office",
    assemblyRequired: true,
    warrantyPeriod: 12,
    loadCapacity: 120.0,
    seatingCapacity: 1,
    adjustableFeatures: "Height, Armrests, Recline",
  },
  {
    name: "King Size Bed Frame",
    description: "A robust king-sized bed frame with a modern finish.",
    price: 999.99,
    stock: 3,
    category: "Bed",
    brand: "DreamSleep",
    imageUrl: "https://example.com/images/king-size-bed.jpg",
    material: "Metal and Wood",
    dimensions: "200x180x45 cm",
    weight: 85.0,
    color: "White",
    style: "Contemporary",
    room: "Bedroom",
    assemblyRequired: true,
    warrantyPeriod: 24,
    loadCapacity: 400.0,
    seatingCapacity: null,
    adjustableFeatures: null,
  },
  {
    name: "Glass Coffee Table",
    description: "A stylish coffee table with a tempered glass top.",
    price: 299.99,
    stock: 15,
    category: "Table",
    brand: "ModernLiving",
    imageUrl: "https://example.com/images/glass-coffee-table.jpg",
    material: "Glass and Metal",
    dimensions: "120x60x45 cm",
    weight: 30.0,
    color: "Clear and Silver",
    style: "Modern",
    room: "Living Room",
    assemblyRequired: false,
    warrantyPeriod: 18,
    loadCapacity: 50.0,
    seatingCapacity: null,
    adjustableFeatures: null,
  },
];

export async function createProducts(prisma: PrismaClient) {
  await prisma.product.createMany({
    data: products,
  });
}
