import { PrismaClient } from "@prisma/client/extension";

const products = [
  {
    id: "1c1e0c90-7f2e-4b90-9f2e-1e9a537d6ad7",
    name: "Modern Sofa",
    description:
      "A comfortable and stylish modern sofa perfect for any living room.",
    price: 499.99,
    stock: 20,
    category: "Furniture",
    brand: "ComfortPlus",
    imageUrl: "https://example.com/images/modern-sofa.jpg",
    createdAt: "2025-01-08T10:00:00Z",
    updatedAt: "2025-01-08T10:00:00Z",
    material: "Leather",
    dimensions: "80x35x30 inches",
    weight: 70.5,
    color: "Gray",
    style: "Modern",
    room: "Living Room",
    assemblyRequired: true,
    warrantyPeriod: 12,
    loadCapacity: 500.0,
    seatingCapacity: 3,
    adjustableFeatures: "Reclining backrest",
  },
  {
    id: "ab6fba32-9f3a-45d2-9b4e-7f345ac234d6",
    name: "Ergonomic Office Chair",
    description: "A high-quality ergonomic office chair with lumbar support.",
    price: 149.99,
    stock: 50,
    category: "Office Supplies",
    brand: "WorkSmart",
    imageUrl: "https://example.com/images/ergonomic-chair.jpg",
    createdAt: "2025-01-08T10:00:00Z",
    updatedAt: "2025-01-08T10:00:00Z",
    material: "Mesh",
    dimensions: "25x25x45 inches",
    weight: 25.0,
    color: "Black",
    style: "Contemporary",
    room: "Office",
    assemblyRequired: true,
    warrantyPeriod: 24,
    loadCapacity: 300.0,
    seatingCapacity: 1,
    adjustableFeatures: "Height, armrests, backrest",
  },
  {
    id: "b972fae0-4bdc-45fc-b3f8-8f6e4c3d9b52",
    name: "Dining Table Set",
    description: "A beautiful dining table set with six chairs.",
    price: 899.99,
    stock: 10,
    category: "Dining",
    brand: "Elegance",
    imageUrl: "https://example.com/images/dining-table-set.jpg",
    createdAt: "2025-01-08T10:00:00Z",
    updatedAt: "2025-01-08T10:00:00Z",
    material: "Wood",
    dimensions: "72x40x30 inches",
    weight: 150.0,
    color: "Dark Walnut",
    style: "Traditional",
    room: "Dining Room",
    assemblyRequired: true,
    warrantyPeriod: 36,
    loadCapacity: null,
    seatingCapacity: 6,
    adjustableFeatures: null,
  },
  {
    id: "6b4c3d72-d5b3-4c3d-80f6-96a12f7e3c5d",
    name: "King Size Bed Frame",
    description:
      "A sturdy and elegant king-size bed frame with a sleek design.",
    price: 299.99,
    stock: 15,
    category: "Bedroom",
    brand: "Dreamland",
    imageUrl: "https://example.com/images/king-size-bed.jpg",
    createdAt: "2025-01-08T10:00:00Z",
    updatedAt: "2025-01-08T10:00:00Z",
    material: "Metal",
    dimensions: "80x76x14 inches",
    weight: 85.0,
    color: "Black",
    style: "Minimalist",
    room: "Bedroom",
    assemblyRequired: true,
    warrantyPeriod: 12,
    loadCapacity: 1000.0,
    seatingCapacity: null,
    adjustableFeatures: null,
  },
  {
    id: "8e5d2c3d-a2f3-4b3c-94f2-b4f6e2d9a8c7",
    name: "Outdoor Patio Set",
    description:
      "A weather-resistant outdoor patio set with a table and four chairs.",
    price: 399.99,
    stock: 25,
    category: "Outdoor",
    brand: "PatioPro",
    imageUrl: "https://example.com/images/outdoor-patio-set.jpg",
    createdAt: "2025-01-08T10:00:00Z",
    updatedAt: "2025-01-08T10:00:00Z",
    material: "Aluminum",
    dimensions: "60x36x30 inches (table)",
    weight: 80.0,
    color: "White",
    style: "Rustic",
    room: "Outdoor",
    assemblyRequired: true,
    warrantyPeriod: 12,
    loadCapacity: null,
    seatingCapacity: 4,
    adjustableFeatures: null,
  },
];

export async function createProducts(prisma: PrismaClient) {
  await prisma.product.createMany({
    data: products,
  });
}
